[package]
name = "rocket_jwt_auth"
version = "0.0.3"
edition = "2021"
license = "MIT"
description = "JWT header authentication for Rocket"
keywords = ["rocket", "jwt"]

[dependencies]
rocket = "0.4.7"
